### ISSUE TITLE
Docker image issues (java.lang.OutOfMemoryError: Java heap space)

### ISSUE THREAD

**Issue by AndriusFromLTU** [mroth/scalafmt-native#7]
Good day,

I tried to update scalafmt version, but couldn't manage to build the provided image at all. Kept getting the exception:
```
Caused by: java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
Error: Image build request failed with exit status 1
```
Also tried incresing the heap to 10g just for it work, but no luck.
The full stack trace:
```
Error: Error encountered while parsing scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$1(scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances, scala.meta.Tree)
Parsing context:
	parsing scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances$$Lambda$1950/1344541596.apply(Unknown Source)
	parsing scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	parsing scala.meta.prettyprinters.Api$XtensionSyntax.syntax(Api.scala:11)
	parsing org.scalafmt.internal.FormatOps.isMarginizedString(FormatOps.scala:254)
	parsing org.scalafmt.internal.FormatWriter.formatMarginizedString(FormatWriter.scala:102)
	parsing org.scalafmt.internal.FormatWriter.$anonfun$mkString$1(FormatWriter.scala:30)
	parsing org.scalafmt.internal.FormatWriter.$anonfun$mkString$1$adapted(FormatWriter.scala:24)
	parsing org.scalafmt.internal.FormatWriter$$Lambda$828/1380444705.apply(Unknown Source)
	parsing org.scalafmt.internal.FormatWriter.$anonfun$reconstructPath$2(FormatWriter.scala:216)
	parsing org.scalafmt.internal.FormatWriter.$anonfun$reconstructPath$2$adapted(FormatWriter.scala:166)
	parsing org.scalafmt.internal.FormatWriter$$Lambda$831/2069414639.apply(Unknown Source)
	parsing scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	parsing scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	parsing scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	parsing scala.collection.TraversableOnce.addString(TraversableOnce.scala:362)
	parsing scala.collection.TraversableOnce.addString$(TraversableOnce.scala:358)
	parsing scala.collection.AbstractIterator.addString(Iterator.scala:1429)
	parsing scala.collection.TraversableOnce.mkString(TraversableOnce.scala:328)
	parsing scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:327)
	parsing scala.collection.AbstractIterator.mkString(Iterator.scala:1429)
	parsing scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:147)
	parsing org.scalafmt.cli.CliOptions.toString(CliOptions.scala:106)
	parsing java.lang.String.valueOf(String.java:2994)
	parsing java.lang.StringBuilder.append(StringBuilder.java:131)
	parsing com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:179)
	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:129)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$1(scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances, scala.meta.Tree)
Parsing context:
	parsing scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances$$Lambda$1950/1344541596.apply(Unknown Source)
	parsing scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	parsing scala.meta.prettyprinters.Api$XtensionSyntax.syntax(Api.scala:11)
	parsing org.scalafmt.internal.FormatOps.isMarginizedString(FormatOps.scala:254)
	parsing org.scalafmt.internal.FormatWriter.formatMarginizedString(FormatWriter.scala:102)
	parsing org.scalafmt.internal.FormatWriter.$anonfun$mkString$1(FormatWriter.scala:30)
	parsing org.scalafmt.internal.FormatWriter.$anonfun$mkString$1$adapted(FormatWriter.scala:24)
	parsing org.scalafmt.internal.FormatWriter$$Lambda$828/1380444705.apply(Unknown Source)
	parsing org.scalafmt.internal.FormatWriter.$anonfun$reconstructPath$2(FormatWriter.scala:216)
	parsing org.scalafmt.internal.FormatWriter.$anonfun$reconstructPath$2$adapted(FormatWriter.scala:166)
	parsing org.scalafmt.internal.FormatWriter$$Lambda$831/2069414639.apply(Unknown Source)
	parsing scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	parsing scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	parsing scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	parsing scala.collection.TraversableOnce.addString(TraversableOnce.scala:362)
	parsing scala.collection.TraversableOnce.addString$(TraversableOnce.scala:358)
	parsing scala.collection.AbstractIterator.addString(Iterator.scala:1429)
	parsing scala.collection.TraversableOnce.mkString(TraversableOnce.scala:328)
	parsing scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:327)
	parsing scala.collection.AbstractIterator.mkString(Iterator.scala:1429)
	parsing scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:147)
	parsing org.scalafmt.cli.CliOptions.toString(CliOptions.scala:106)
	parsing java.lang.String.valueOf(String.java:2994)
	parsing java.lang.StringBuilder.append(StringBuilder.java:131)
	parsing com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:179)
	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:129)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
Error: Image build request failed with exit status 1
```

**Comment by mroth** [comment]
@myDisconnect can you submit the changes for this as a PR?  Then we should be able to see the output in CI and debug together. Thanks!
